// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChekPAkpC_sr1LQF0bSXC8ob2HuhydtQ',
    appId: '1:831366721192:android:5c98807d54fdb76ac99c9d',
    messagingSenderId: '831366721192',
    projectId: 'magazincha-4d6c6',
    databaseURL: 'https://magazincha-4d6c6-default-rtdb.firebaseio.com',
    storageBucket: 'magazincha-4d6c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCloXf7OrGQR3N5nfjAXUPpn--XTru3o7U',
    appId: '1:831366721192:ios:4e990e964e0d5262c99c9d',
    messagingSenderId: '831366721192',
    projectId: 'magazincha-4d6c6',
    databaseURL: 'https://magazincha-4d6c6-default-rtdb.firebaseio.com',
    storageBucket: 'magazincha-4d6c6.appspot.com',
    iosBundleId: 'com.example.verySimpleOnlineShopCubit',
  );
}
